version: '2'
services:
  site:
    build: .
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=Pa55word
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PERMISSIONS=b
      - ADMIN_FULLNAME=Admin
      - ADMIN_TITLE=SiteAdmin
      - DOMAIN=localhost    # set to your root/apex domain
      - GENERATE_CERTS=false  # set to true to automatically setup trusted ssl with let's encrypt
